version: '3'

networks:
   local:

services:
   mysql:
      container_name: mysqldb
      image: mysql:8
      command: --default-authentication-plugin=mysql_native_password
      environment:
         MYSQL_DATABASE: blogdb
         MYSQL_USER: blog
         MYSQL_PASSWORD: blog
         MYSQL_ROOT_PASSWORD: root
      networks:
         - local
      ports:
         - '3306:3306'

   app:
      depends_on:
         - mysql
      container_name: blog-api
      build:
         context: .
         dockerfile: Dockerfile
      environment:
         DB_HOST: mysql
         DB_USERNAME: blog
         DB_PASSWORD: blog
         DB_DATABASE: blogdb
      volumes:
         - ./:/home/app
      ports:
         - '3000:3000'
      networks:
         - local
