version: '3.5'

networks:
   local:

services:
   mysql:
      container_name: mysqlblogdb
      image: mysql:8
      command: --default-authentication-plugin=mysql_native_password
      environment:
         MYSQL_DATABASE: ${MYSQL_DATABASE}
         MYSQL_USER: ${MYSQL_USER}
         MYSQL_PASSWORD: ${MYSQL_PASSWORD}
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      networks:
         - local
      ports:
         - '3306:3306'

   app:
      depends_on:
         - mysql
      container_name: blog-api
      build: .
      environment:
         DB_HOST: ${DB_HOST}
         DB_USERNAME: ${DB_USERNAME}
         DB_PASSWORD: ${DB_PASSWORD}
         DB_DATABASE: ${DB_DATABASE}
      volumes:
         - ./:/blog-api
         - /blog-api/node_modules
      ports:
         - '4000:4000'
      networks:
         - local
